swagger: '2.0'
info:
  title: REST API
  version: 1.0.0
  description: Example docs
host: localhost:5000
schemes:
  - http
  - https

tags:
  - name: users
    description: users API
  - name: metadata
    description: Metadata API
  - name: quickcode
    description: Quickcode API

paths:
  /users:
    get:
      tags:
        - users
      summary: Find All Users
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

    post:
      tags:
        - users
      summary: Add User
      parameters:
        - name: body
          in: body
          description: User Data
          required: true
          schema:
            $ref: '#/definitions/users'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  /users/{id}:
    get:
      tags:
        - users
      summary: Find User By Id
      parameters:
        - name: id
          in: path
          description: User Id
          required: true
          type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    put:
      tags:
        - users
      summary: Update User By Id
      parameters:
        - name: id
          in: path
          description: User Id
          required: true
          type: integer
        - name: body
          in: body
          description: User Data
          required: true
          schema:
            $ref: '#/definitions/users'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    delete:
      tags:
        - users
      summary: Delete User By Id
      parameters:
        - name: id
          in: path
          description: User Id
          required: true
          type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  /metadata:
    post:
      tags:
        - metadata
      summary: Insert Metadata
      parameters:
        - name: body
          in: body
          description: Metadata information
          required: true
          schema:
            $ref: '#/definitions/Metadata'
      responses:
        201:
          description: 'Created'
        500:
          description: 'Server Error'

  /quickcode:
    post:
      tags:
        - quickcode
      summary: Insert Quickcode
      parameters:
        - name: body
          in: body
          description: Quickcode information
          required: true
          schema:
            $ref: '#/definitions/Quickcode'
      responses:
        201:
          description: Created
        400:
          description: Bad Request
        500:
          description: Server Error

  /test:
    get:
      tags:
        - Test
      summary: Test endpoint
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Test endpoint working

definitions:
  users:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
        description: User Email
      password:
        type: string
        description: User Password

  Metadata:
    type: object
    required:
      - screen_code
      - meta_code
      - screen_name
      - meta_code_name
    properties:
      screen_code:
        type: string
        description: Screen Code
      meta_code:
        type: string
        description: Meta Code
      screen_name:
        type: string
        description: Screen Name
      meta_code_name:
        type: string
        description: Meta Code Name

  Quickcode:
    type: object
    required:
      - quick_code_type
      - quick_code
      - language_code
      - quickcode_name
    properties:
      quick_code_type:
        type: string
        description: Quick Code Type
      quick_code:
        type: string
        description: Quick Code
      language_code:
        type: integer
        description: Language Code
      quickcode_name:
        type: string
        description: Quickcode Name
      concurrency_val:
        type: integer
        description: Concurrency Value
      created_by:
        type: string
        description: Created By
      created_date:
        type: string
        format: date-time
        description: Created Date
        required: false
      updated_by:
        type: string
        description: Updated By
      updated_date:
        type: string
        format: date-time
        description: Updated Date
        required: false
